services:
  db:
    image: postgres:17-alpine
    container_name: name
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    ports:
      - "5437:5432"
    volumes:
      - database_vol:/var/lib/postgresql/data
    networks:
      - alpha_network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile 
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DB_USER=agent_user
      - DB_NAME=hotel_db
      - DB_PASS=agent_pwd
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - alpha_network

  llm:
    build: 
      context: ./llm
      dockerfile: Dockerfile 
    depends_on:
      - api
    restart: unless-stopped
    environment:
      - API_BASE_URL=https://hotel-agent.redalab.org
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_NIM_API_KEY=${NVIDIA_NIM_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - PORT=8005
    ports:
      - "8005:8005"
    volumes:
      - ./llm:/app
    networks:
      - alpha_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
      - llm
    restart: unless-stopped
    environment:
      - API_URL=https://hotel-api.sokhengdin.dev
      - LLM_URL=https://hotel-llm.sokhengdin.dev
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://hotel-llm.sokhengdin.dev/api/v1
    ports:
      - "3000:3000"
    networks:
      - alpha_network

volumes:
  database_vol:

networks:
  alpha_network:
    external: true