services:
  db:
    image: postgres:17-alpine
    container_name: name
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    ports:
      - "5437:5432"
    volumes:
      - database_agent_volume:/var/lib/postgresql/data
    networks:
      - ams_network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile 
    container_name: hotel_agent_api
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./api:/app
    networks:
      - ams_network

  llm:
    build: 
      context: ./llm
      dockerfile: Dockerfile 
    container_name: hotel_agent_llm
    depends_on:
      - api
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://hotel_agent_api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_NIM_API_KEY=${NVIDIA_NIM_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - PORT=8005
    ports:
      - "8005:8005"
    volumes:
      - ./llm:/app
      - ./upload:/app/uploads
    networks:
      - ams_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
      - llm
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://hotel_agent_api:8000
      - NEXT_PUBLIC_LLM_API_URL=http://hotel_agent_llm:8005
      - NODE_ENV=production
    networks:
      - ams_network

volumes:
  database_agent_volume:

networks:
  ams_network:
    external: true